# Generated by Django 6.0.2 on 2026-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='weather_type',
            field=models.CharField(choices=[('Clear', 'Clear'), ('Sunny', 'Sunny'), ('Clouds', 'Clouds'), ('Rain', 'Rain'), ('Snow', 'Snow'), ('Drizzle', 'Drizzle'), ('Thunderstorm', 'Thunderstorm'), ('Mist', 'Mist'), ('Smoke', 'Smoke'), ('Haze', 'Haze'), ('Dust', 'Dust'), ('Fog', 'Fog'), ('Sand', 'Sand'), ('Ash', 'Ash'), ('Squall', 'Squall'), ('Tornado', 'Tornado')], default='Clear', max_length=20),
        ),
    ]
